Emit error if no container or image could be found.

diff --git a/bin/docker-shell b/bin/docker-shell
--- a/bin/docker-shell
+++ b/bin/docker-shell
@@ -4,6 +4,9 @@ CONTAINER_ID=$(docker ps | grep "${1/:/ *}" | head -1 | awk '{ print $1 }')
 IMAGE_ID=$(docker images | grep "${1/:/ *}" | head -1 | awk '{ print $3 }')
 if [ -n "$CONTAINER_ID" ];then
    docker exec --interactive --tty $CONTAINER_ID /bin/bash
-else
+elif [ -n "$IMAGE_ID" ];then
    docker run --interactive --entrypoint /bin/bash --tty $IMAGE_ID
+else
+   echo "ERROR: no container or image matched '$1'"
+   exit 1
 fi
